# Generated by Django 3.0.6 on 2021-07-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0003_auto_20210711_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benhnhan',
            options={'verbose_name': 'benhnhan', 'verbose_name_plural': 'benhnhan'},
        ),
        migrations.AddField(
            model_name='benhnhan',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
