# Generated by Django 3.0.6 on 2021-07-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0004_auto_20210711_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhasi',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
