# Generated by Django 3.0.6 on 2021-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0005_nhasi_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='canhbao',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diung',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trieuchung',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
