# Generated by Django 3.0.6 on 2021-07-11 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0006_auto_20210711_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='benhnhan',
            name='ngay_kham',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
