# Generated by Django 3.0.6 on 2021-07-11 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0008_auto_20210711_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='benhnhan',
            name='ho_ten_nha_si',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
