# Generated by Django 3.0.6 on 2021-07-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0010_auto_20210712_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benhnhan',
            name='ngay_kham',
        ),
    ]
