# Generated by Django 3.0.6 on 2021-07-13 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0011_remove_benhnhan_ngay_kham'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benhnhan',
            name='kham_den_ngay',
        ),
        migrations.AddField(
            model_name='benhnhan',
            name='ghi_Chu',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benhnhan',
            name='thoi_gian_kham',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
