# Generated by Django 3.0.6 on 2021-07-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0012_auto_20210713_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benhnhan',
            old_name='ghi_Chu',
            new_name='ghi_chu',
        ),
    ]
