# Generated by Django 3.0.6 on 2021-07-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0013_auto_20210713_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThoiGian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
