# Generated by Django 3.0.6 on 2021-07-13 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0014_thoigian'),
    ]

    operations = [
        migrations.AddField(
            model_name='benhnhan',
            name='noi_dung_kham',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
