# Generated by Django 3.0.6 on 2021-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0016_auto_20210714_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='ma_ho_so',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
