# Generated by Django 3.0.6 on 2021-07-17 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0017_auto_20210715_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichlamviec',
            name='ho_ten_nha_si',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
