# Generated by Django 3.0.6 on 2021-07-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0018_lichlamviec_ho_ten_nha_si'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lichlamviec',
            old_name='lam_viec_den_gio',
            new_name='ma_so_nha_si',
        ),
        migrations.RenameField(
            model_name='lichlamviec',
            old_name='lam_viec_tu_gio',
            new_name='thoi_gian_nghi',
        ),
        migrations.RemoveField(
            model_name='lichlamviec',
            name='lam_viec_den_ngay',
        ),
        migrations.RemoveField(
            model_name='lichlamviec',
            name='lam_viec_tu_ngay',
        ),
        migrations.RemoveField(
            model_name='lichlamviec',
            name='nha_si',
        ),
    ]
