# Generated by Django 3.0.6 on 2021-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhasi', '0019_auto_20210719_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='ma_so_nha_si',
            field=models.CharField(max_length=50),
        ),
    ]
